development:
 adapter: mysql2
 encoding: utf8
 database: study_development
 pool: 5
 username: root
 password: root

test:
 adapter: mysql2
 encoding: utf8
 database: study_test
 pool: 5
 username: root
 password:
